import 'property.dart';
import 'property_type.dart';
import 'agent.dart';

class AppData {
  static final List<PropertyType> propertyTypes = [
    PropertyType(
      id: '1',
      name: 'Rumah',
      icon: 'assets/icons/rumah.png',
    ),
    PropertyType(
      id: '2',
      name: 'Kontrakkan',
      icon: 'assets/icons/kontrakkan.png',
    ),
    PropertyType(
      id: '3',
      name: 'Kos',
      icon: 'assets/icons/kos.png',
    ),
    PropertyType(
      id: '4',
      name: 'Apartemen',
      icon: 'assets/icons/apartemen.png',
    ),
    PropertyType(
      id: '5',
      name: 'Tanah',
      icon: 'assets/icons/tanah.png',
    ),
  ];

  static final List<Agent> agents = [
    Agent(
      id: '1',
      name: 'Septiawan',
      email: 'septiawan@gmail.com',
      phone: '+62812345678',
      photo: 'assets/agents/wawan.jpg',
      properties: ['1', '2', '3'],
    ),
    Agent(
      id: '2',
      name: 'Daniel lim',
      email: 'sensei@gmail.com',
      phone: '+62876543210',
      photo: 'assets/agents/sensei.jpg',
      properties: ['3', '4'],
    ),
    Agent(
      id: '3',
      name: 'Roid lumban tobing',
      email: 'roid@gmail.com',
      phone: '+62876543210',
      photo: 'assets/agents/roid.jpg',
      properties: ['3', '4'],
    ),
    Agent(
      id: '4',
      name: 'Nabil Syawaludin prima',
      email: 'nabil@gmail.com',
      phone: '+62876543210',
      photo: 'assets/agents/nabil.jpg',
      properties: ['3', '4'],
    ),
    Agent(
      id: '5',
      name: 'Dedi manalu',
      email: 'dedi@gmail.com',
      phone: '+62876543210',
      photo: 'assets/agents/dedi.jpg',
      properties: ['3', '4'],
    ),
  ];

  static final List<Property> properties = [
    Property(
      id: '1',
      name: 'Rumah dengan warna pink',
      location: 'Jalan soak simpur komplek griya buana indah',
      price: '280.000.000',
      beds: 2,
      baths: 1,
      description:
          "Rumah dengan desain menarik dan warna pink cerah ini terletak di lokasi strategis di Komplek Griya Buana Indah. Dengan dua kamar tidur, satu kamar mandi, dan luas bangunan 100 m², rumah ini cocok untuk keluarga kecil. Selain itu, terdapat fasilitas tempat parkir yang memadai. Dilengkapi dengan Sertifikat Hak Milik (SHM) dan berada di lantai pertama, menjadikannya pilihan yang aman dan nyaman.",
      images: [
        'assets/images/rumahpertama.jpg',
        'assets/images/rumahpertama.jpg',
      ],
      type: '1',
      isFeatured: true,
      agent: '1',
      postingDay: '10 Januari 2025',
      buildingArea: '100',
      certificate: 'SHM - Sertifikat Hak Milik',
      facility: 'Tempat mobil',
      surfaceArea: '130',
      floor: '1',
    ),
    Property(
      id: '2',
      name: 'Rumah dengan warna oranye',
      location: 'Jl. Palem Raya 60-6, 15 Ulu, Kecamatan Seberang Ulu I',
      price: '440.000.000',
      beds: 3,
      baths: 2,
      description:
          "Rumah dengan warna abu-abu yang elegan ini memiliki tiga kamar tidur dan dua kamar mandi, memberikan kenyamanan lebih bagi keluarga besar. Dengan luas bangunan 100 m² dan tanah 130 m², rumah ini dilengkapi dengan fasilitas parkir yang luas. Dilengkapi dengan Sertifikat Hak Milik (SHM), rumah ini merupakan investasi yang aman di kawasan Bukit Sangkal.",
      images: [
        'assets/images/rumahkedua.jpg',
        'assets/images/rumahkedua.jpg',
      ],
      type: '1',
      isFeatured: true,
      agent: '1',
      postingDay: '2 Januari 2025',
      buildingArea: '100',
      certificate: 'SHM - Sertifikat Hak Milik',
      facility: 'Tempat mobil',
      surfaceArea: '130',
      floor: '1',
    ),
    Property(
      id: '3',
      name: 'Rumah warna abu-abu',
      location: 'Bukit Sangkal, Kec. Kalidoni, Kota Palembang',
      price: '500.000.000',
      beds: 3,
      baths: 2,
      description:
          "Kontrakan dengan warna kuning cerah ini adalah pilihan tepat bagi mahasiswa atau pekerja yang membutuhkan tempat tinggal praktis dan nyaman. Terletak di Apartemen The City, dengan dua kamar tidur dan satu kamar mandi, tempat ini juga dilengkapi dengan fasilitas AC, water heater, dan dapur kecil. Dengan luas bangunan 30 m² dan sertifikat hak milik, kontrakan ini menawarkan kenyamanan dengan harga terjangkau.",
      images: [
        'assets/images/rumahketiga.jpg',
        'assets/images/rumahketiga.jpg',
      ],
      type: '1',
      isFeatured: true,
      agent: '1',
      postingDay: '13 Januari 2025',
      buildingArea: '100',
      certificate: 'SHM - Sertifikat Hak Milik',
      facility: 'Tempat mobil',
      surfaceArea: '130',
      floor: '1',
    ),
    Property(
      id: '4',
      name: 'Kontrakan warna kuning',
      location: 'Apartemen The City, Jl. Raya No. 25, Palembang',
      price: '800.000/bulan',
      beds: 2,
      baths: 1,
      description:
          "Apartemen studio dengan fasilitas lengkap, cocok untuk mahasiswa atau pekerja yang membutuhkan tempat tinggal nyaman. Lokasi strategis dekat dengan transportasi umum, restoran, dan pusat perbelanjaan. Apartemen ini sudah dilengkapi dengan AC, water heater, dan dapur kecil.",
      images: [
        'assets/images/kontrakkanpertama.jpg',
        'assets/images/kontrakkanpertama.jpg',
      ],
      type: '2',
      isFeatured: true,
      agent: '2',
      postingDay: '16 Januari 2025',
      buildingArea: '30',
      certificate: 'Sertifikat Hak Milik',
      facility: 'AC, water heater, dapur kecil',
      surfaceArea: '40',
      floor: '1',
    ),
    Property(
      id: '5',
      name: 'Kontrakan warna pink',
      location: 'Apartemen The City, Jl. Raya No. 25, Palembang',
      price: '1.000.000/bulan',
      beds: 2,
      baths: 1,
      description:
          "Apartemen studio dengan fasilitas lengkap, cocok untuk mahasiswa atau pekerja yang membutuhkan tempat tinggal nyaman. Lokasi strategis dekat dengan transportasi umum, restoran, dan pusat perbelanjaan. Apartemen ini sudah dilengkapi dengan AC, water heater, dan dapur kecil.",
      images: [
        'assets/images/kontrakkankedua.jpg',
        'assets/images/kontrakkankedua.jpg',
      ],
      type: '2',
      isFeatured: true,
      agent: '2',
      postingDay: '16 Januari 2025',
      buildingArea: '30',
      certificate: 'Sertifikat Hak Milik',
      facility: 'AC, water heater, dapur kecil',
      surfaceArea: '40',
      floor: '1',
    ),
    Property(
      id: '6',
      name: 'Kos-Kosan Kamar Kecil',
      location: 'Jl. Pemuda No. 10, Palembang, Sumatera Selatan',
      price: '1.500.000/bulan',
      beds: 1,
      baths: 1,
      description:
          "Kos-kosan dengan kamar kecil yang cocok untuk mahasiswa atau pekerja dengan harga terjangkau. Lokasi strategis di pusat kota dan dekat dengan kampus serta fasilitas umum seperti minimarket dan transportasi umum. Kamar sudah dilengkapi dengan kasur, lemari pakaian, dan meja kecil. Lingkungan yang aman dan nyaman, dengan akses 24 jam.",
      images: [
        'assets/images/kospertama.jpg',
        'assets/images/kospertama.jpg',
      ],
      type: '3',
      isFeatured: false,
      agent: '3',
      postingDay: '17 Januari 2025',
      buildingArea: '20',
      certificate: 'Tidak ada',
      facility: 'Kasur, lemari pakaian, meja kecil',
      surfaceArea: '25',
      floor: '1',
    ),
    Property(
      id: '7',
      name: 'Apartemen 2 Kamar Tidur',
      location: 'Apartemen Park View, Jl. Sejahtera No. 12, Palembang',
      price: '2.000.000/bulan',
      beds: 2,
      baths: 1,
      description:
          "Apartemen dengan 2 kamar tidur dan 1 kamar mandi, cocok untuk keluarga kecil atau pasangan yang membutuhkan tempat tinggal yang nyaman dan strategis. Apartemen ini dilengkapi dengan ruang tamu luas, dapur modern, serta fasilitas AC dan water heater. Lokasi dekat dengan pusat perbelanjaan, sekolah, dan akses transportasi umum.",
      images: [
        'assets/images/apartemenpertama.jpg',
        'assets/images/apartemenpertama.jpg',
      ],
      type: '4',
      isFeatured: true,
      agent: '4',
      postingDay: '18 Januari 2025',
      buildingArea: '75',
      certificate: 'Sertifikat Hak Milik',
      facility: 'AC, water heater, dapur modern, ruang tamu',
      surfaceArea: '90',
      floor: '5',
    ),
    Property(
      id: '8',
      name: 'Tanah Strategis di Pusat Kota',
      location: 'Jl. Raya Pahlawan No. 8, Palembang, Sumatera Selatan',
      price: '1.200.000.000',
      beds: 0,
      baths: 0,
      description:
          "Tanah kosong dengan luas 200 meter persegi, terletak di lokasi strategis di pusat kota. Sangat cocok untuk investasi, pembangunan rumah, atau proyek komersial seperti ruko. Akses mudah ke jalan utama dan dekat dengan fasilitas umum seperti sekolah, pasar, dan transportasi umum. Sertifikat hak milik (SHM) lengkap dan aman.",
      images: [
        'assets/images/tanahpertama.jpg',
        'assets/images/tanahpertama.jpg',
      ],
      type: '5',
      isFeatured: true,
      agent: '5',
      postingDay: '19 Januari 2025',
      buildingArea: '0',
      certificate: 'SHM - Sertifikat Hak Milik',
      facility: 'Akses jalan utama, lokasi strategis',
      surfaceArea: '200',
      floor: '0',
    ),
    Property(
      id: '9',
      name: 'Tanah Strategis di Pusat Kota',
      location: 'Jl. Raya Pahlawan No. 8, Palembang, Sumatera Selatan',
      price: '1.200.000.000',
      beds: 0,
      baths: 0,
      description:
          "Tanah kosong dengan luas 200 meter persegi, terletak di lokasi strategis di pusat kota. Sangat cocok untuk investasi, pembangunan rumah, atau proyek komersial seperti ruko. Akses mudah ke jalan utama dan dekat dengan fasilitas umum seperti sekolah, pasar, dan transportasi umum. Sertifikat hak milik (SHM) lengkap dan aman.",
      images: [
        'assets/images/tanahkedua.jpg',
        'assets/images/tanahkedua.jpg',
      ],
      type: '5',
      isFeatured: true,
      agent: '5',
      postingDay: '19 Januari 2025',
      buildingArea: '0',
      certificate: 'SHM - Sertifikat Hak Milik',
      facility: 'Akses jalan utama, lokasi strategis',
      surfaceArea: '200',
      floor: '0',
    )
  ];
}
